#!/usr/bin/env ruby

# Concepts learned approximation

# Concepts learned (broken down by male/female (if reported) and all)

# For each course (course 1-4, K8, HOC of courses):
# Finished 100% of puzzles in the course
# Finished 90% of puzzles in the course
# Finished 80% of the puzzles in the course
# …
# Finished 10% of the puzzles
# Started the course

# And also by stage or HOC class (specific concepts)
# Stage 1:
# Number of students who had optimal solutions to all puzzles
# Number of students who finished all puzzles
# Number of students who finished 80%
# Stage 2:
# etc.
# etc.
require_relative '../../config/environment'
connection = ActiveRecord::Base.connection
script_data = Script.all.map do |script|
  sql = "select query, count(*) from (SELECT count(*) as query from user_levels where script_id = #{script.id} group by user_id) as derived_table group by query"
  {id: script.id, data: connection.execute(sql)}.to_json.tap{|x|puts x}
end
puts script_data.to_json
